{% set name = "localtileserver" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8068d251f249557ca7f51ed3510f3d077d1e640a5f68bddff2a41aa4667b33ca

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - localtileserver = localtileserver.__main__:run_app

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - GDAL >=3
    - click
    - large-image >=1.13
    - large-image-source-gdal >=1.13
    - flask >=2.0.0
    - flask-caching
    - flask-restx >=0.5.0
    - requests
    - scooby

test:
  imports:
    - large_image_source_gdal
    - localtileserver

about:
  home: https://github.com/banesullivan/localtileserver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Local tile server for viewing geospatial raster files with ipyleaflet or folium
  description: |
    Need to visualize a rather large (gigabytes) raster you have locally? This is for you. Local tile server for viewing geospatial raster files with ipyleaflet or folium. A Flask application for serving tiles from large raster files in the Slippy Maps standard (i.e., `/zoom/x/y.png`).
  doc_url: https://github.com/banesullivan/localtileserver/blob/main/README.md
  dev_url: https://github.com/banesullivan/localtileserver

extra:
  recipe-maintainers:
    - banesullivan
    - giswqs
