{% set name = "localtileserver" %}
{% set version = "0.3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c022f37ee51e54714657bbc2890b5e77582d94185f45b37c4da566ebbfa9f549

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - localtileserver = localtileserver.__main__:run_app

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - GDAL >=3
    - large-image-source-gdal
    - flask >=2.0.0
    - flask-caching
    - requests
    - scooby
    - ipyleaflet
    - folium

test:
  imports:
    - large_image_source_gdal
    - localtileserver

about:
  home: https://github.com/banesullivan/localtileserver
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Local tile server for viewing geospatial raster files with ipyleaflet or folium
  description: |
    Need to visualize a rather large (gigabytes) raster you have locally? This is for you. Local tile server for viewing geospatial raster files with ipyleaflet or folium. A Flask application for serving tiles from large raster files in the Slippy Maps standard (i.e., `/zoom/x/y.png`).
  doc_url: https://github.com/banesullivan/localtileserver/blob/main/README.md
  dev_url: https://github.com/banesullivan/localtileserver

extra:
  recipe-maintainers:
    - banesullivan
    - giswqs
